# Uncomment the next line to define a global platform for your project
platform :osx, '10.12'

workspace "iGlance"

use_frameworks!

pod "SwiftLint"
pod "CocoaLumberjack/Swift"

target 'iGlance' do
  workspace "iGlance"
  project "iGlance/iGlance.xcodeproj"
  
  # Pods for iGlance
  pod "Sparkle"
end

target "SMCKit" do
  workspace "iGlance"
  project "Libraries/SMCKit/SMCKit.xcodeproj"
end

target "SystemKit" do
  workspace "iGlance"
  project "Libraries/SystemKit/SystemKit.xcodeproj"
end

target "AppMover" do
  workspace "iGlance"
  project "Libraries/AppMover/AppMover.xcodeproj"
end

post_install do |installer|
     installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
             config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.9'
         end
     end
  end