# Uncomment the next line to define a global platform for your project
platform :osx, '10.6'

target 'iGlance' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iGlance
  pod "SwiftLint"
  
  target 'iGlanceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iGlanceUITests' do
    # Pods for testing
  end

end
